modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/Wynnventory/WynnVentory_Mod/issues"
license = "MIT"

[[mods]]
modId = "wynnventory"
version = "${version}"
displayName = "wynnventory"
authors = "Aruloci, SiropBVST"
description = '''
Real-time insights and historical data from the Wynncraft Trade Market.
'''
logoFile = "assets/wynnventory/icon.png"

[[dependencies.wynnventory]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.wynnventory]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "wynnventory.mixins.json"
