modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wynnventory"
version = "${version}"
displayName = "wynnventory"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.wynnventory]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wynnventory]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "wynnventory.mixins.json"
