modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/Wynnventory/WynnVentory_Mod/issues"
license = "MIT"

[[mods]]
modId = "wynnventory"
version = "${mod_version}"
displayName = "wynnventory"
authors = "Aruloci, SiropBVST"
description = '''
Real-time insights and historical data from the Wynncraft Trade Market.
'''
logoFile = "assets/wynnventory/icon.png"

[[dependencies.wynnventory]]
modId = "neoforge"
type = "required"
versionRange = "[{$neoforge_loader_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.wynnventory]]
modId = "minecraft"
type = "required"
versionRange = "[{$minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.wynnventory]]
modId = "wynntils"
type = "required"
reason="integration"
versionRange = "[${wynntils_version},)"
ordering = "NONE"
side = "CLIENT"
referralUrl = "https://modrinth.com/mod/wynntils"

[[mixins]]
config = "wynnventory.mixins.json"
